### ISSUE TITLE
Suggests to install packages from unstable dist tags

### ISSUE THREAD

**Issue by felixfbecker** [dependencies-io/collector-js-npm#17]
npm has the concept of dist-tags, which work like release channels. `npm install` will always pick the version with the `latest` dist-tag (even if there is a higher version with e.g. a `next` dist-tag). Like Greenkeeper, dependencies.io should not do PRs to update to an unstable version.

Example:

Got an "action" for installed version 8.2.0 to update to 9.0.0 even though 8.2.0 is `latest`.

![image](https://user-images.githubusercontent.com/10532611/32139530-20d90696-bc00-11e7-9a68-b7e2d60ba87e.png)

`npm info semantic-release`:
```js
'dist-tags': 
   { latest: '8.2.0',
     alpaca: '3.4.1',
     badger: '4.3.5',
     next: '9.0.0' },
```

**Comment by felixfbecker** [comment]
@davegaeddert what would be the correct fix for this? Have the collector only report versions smaller than `latest`?

**Comment by davegaeddert** [comment]
@felixfbecker take a look at #18 which I just opened. It can get a little complicated to think through all the different scenarios...but I think that will give us a decent start?
