### ISSUE TITLE
Fix how installed version is determined from yarn.lock when a package has multiple versions

### ISSUE THREAD

**Issue by davegaeddert** [dependencies-io/collector-js-npm#23]
It's possible in npm to have multiple versions of a single package installed. In the current implementation, we only want to report the version that would be installed at the root (the others get nested under their parent dependency). 

I naively started by just using the *first* version we saw (which worked for all my tests and research) but clearly isn't right. Are there internal yarn functions we can use for this? Or do we need to find the one with `@{range from package.json}` to know which should be installed for the root package.json? Ideally we could still do this without performing the actual install.

```
lodash@3.10.1, lodash@^3.10.1:
  version "3.10.1"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-3.10.1.tgz#5bf45e8e49ba4189e17d482789dfd15bd140b7b6"

lodash@4, lodash@4.x.x, lodash@^4.0.0, lodash@^4.1.0, lodash@^4.13.1, lodash@^4.14.0, lodash@^4.15.0, lodash@^4.17.2, lodash@^4.17.4, lodash@^4.2.0, lodash@^4.2.1, lodash@^4.3.0, lodash@^4.6.1:
  version "4.17.4"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.4.tgz#78203a4d1c328ae1d86dca6460e369b57f4055ae"

lodash@4.11.1:
  version "4.11.1"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.11.1.tgz#a32106eb8e2ec8e82c241611414773c9df15f8bc"
```

Would have resolved to "3.10.1" installed, when `"lodash": "^4.17.2",` is what package.json asked for so it should have resolved to "4.17.4".

cc @Hypnosphi

**Comment by Hypnosphi** [comment]
`yarn list package-name` may help, I think

**Comment by davegaeddert** [comment]
I went a different direction for now, but may come back to using `yarn list` later. It provides a little more information which would help with some ideas we're working through 😉
